"""empty message

Revision ID: b919bda38d42
Revises: aede8cd191c8
Create Date: 2020-01-12 14:19:44.789986

"""

# revision identifiers, used by Alembic.
revision = 'b919bda38d42'
down_revision = 'aede8cd191c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_posts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='fk_user_posts_post'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_posts_user')
    )
    op.add_column('pages', sa.Column('ghosted_id', sa.Integer(), nullable=True))
    op.add_column('pages', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.alter_column('pages', 'mini',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'pages', 'pages', ['ghosted_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('pages', 'slug')
    op.drop_column('pages', 'base_route')
    op.drop_column('pages', 'is_root')
    op.drop_column('pages', 'ghost')
    op.drop_column('pages', 'timestamp')
    op.add_column('posts', sa.Column('ghosted_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'posts', ['ghosted_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('posts', 'author_id')
    op.drop_column('posts', 'ghost')
    op.drop_column('posts', 'timestamp')
    op.alter_column('uploads', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('fk_user_roles_user', 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_user_roles_role', 'user_roles', 'roles', ['role_id'], ['id'])
    op.drop_column('user_roles', 'id')
    op.add_column('users', sa.Column('fist_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('reset_expiration', sa.DateTime(), nullable=True))
    op.alter_column('users', 'reset_password_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'is_enabled')
    op.drop_column('users', 'confirmed_at')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'personal_bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('personal_bio', sa.VARCHAR(length=1024), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=50), nullable=False))
    op.add_column('users', sa.Column('confirmed_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('is_enabled', sa.BOOLEAN(), nullable=False))
    op.alter_column('users', 'reset_password_token',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_column('users', 'reset_expiration')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'fist_name')
    op.add_column('user_roles', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint('fk_user_roles_role', 'user_roles', type_='foreignkey')
    op.drop_constraint('fk_user_roles_user', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('uploads', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('posts', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('posts', sa.Column('ghost', sa.VARCHAR(length=512), nullable=True))
    op.add_column('posts', sa.Column('author_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.drop_column('posts', 'last_updated')
    op.drop_column('posts', 'ghosted_id')
    op.add_column('pages', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('pages', sa.Column('ghost', sa.VARCHAR(length=512), nullable=True))
    op.add_column('pages', sa.Column('is_root', sa.BOOLEAN(), nullable=True))
    op.add_column('pages', sa.Column('base_route', sa.VARCHAR(length=255), nullable=False))
    op.add_column('pages', sa.Column('slug', sa.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'pages', type_='foreignkey')
    op.alter_column('pages', 'mini',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('pages', 'last_updated')
    op.drop_column('pages', 'ghosted_id')
    op.drop_table('user_posts')
    # ### end Alembic commands ###
